"""add unique constraint to attendance

Revision ID: 2601a02b95ab
Revises: 5974ac818a8c
Create Date: 2026-06-09 06:40:26.327325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2601a02b95ab'
down_revision: Union[str, Sequence[str], None] = '5974ac818a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('attendance_student_semester_uc', 'attendances', ['student_id', 'semester', 'academic_year'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendance_student_semester_uc', 'attendances', type_='unique')
    # ### end Alembic commands ###
