"""add student unique constraints

Revision ID: 3433de3e2864
Revises: 92a1a2943ee3
Create Date: 2026-06-05 12:38:48.072497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3433de3e2864'
down_revision: Union[str, Sequence[str], None] = '92a1a2943ee3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('nisn', sa.String(length=20), nullable=True))
    op.drop_index(op.f('ix_students_nis'), table_name='students')
    op.create_index(op.f('ix_students_nis'), 'students', ['nis'], unique=False)
    op.create_unique_constraint('_tenant_nis_uc', 'students', ['tenant_id', 'nis'])
    op.create_index(op.f('ix_students_nisn'), 'students', ['nisn'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_nisn'), table_name='students')
    op.drop_constraint('_tenant_nis_uc', 'students', type_='unique')
    op.drop_index(op.f('ix_students_nis'), table_name='students')
    op.create_index(op.f('ix_students_nis'), 'students', ['nis'], unique=True)
    op.drop_column('students', 'nisn')
    # ### end Alembic commands ###
