"""add unique constraint to socio economic

Revision ID: 5974ac818a8c
Revises: ba578dd8e6a7
Create Date: 2026-06-09 06:25:32.114509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5974ac818a8c'
down_revision: Union[str, Sequence[str], None] = 'ba578dd8e6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_student_semester_uc', 'academics', ['student_id', 'semester', 'academic_year'])
    op.create_unique_constraint('_student_socio_economic_uc', 'socio_economics', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_student_socio_economic_uc', 'socio_economics', type_='unique')
    op.drop_constraint('_student_semester_uc', 'academics', type_='unique')
    # ### end Alembic commands ###
