"""add index to tenant_id

Revision ID: 92a1a2943ee3
Revises: c97b0bbbefa4
Create Date: 2026-06-05 12:25:54.908201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92a1a2943ee3'
down_revision: Union[str, Sequence[str], None] = 'c97b0bbbefa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_nis'), table_name='students')
    op.create_index(op.f('ix_students_nis'), 'students', ['nis'], unique=True)
    op.create_index(op.f('ix_students_tenant_id'), 'students', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_students_tenant_id'), table_name='students')
    op.drop_index(op.f('ix_students_nis'), table_name='students')
    op.create_index(op.f('ix_students_nis'), 'students', ['nis'], unique=False)
    # ### end Alembic commands ###
