"""add indexes to tenant and student foreign keys

Revision ID: ba578dd8e6a7
Revises: 3433de3e2864
Create Date: 2026-06-06 05:31:32.724917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba578dd8e6a7'
down_revision: Union[str, Sequence[str], None] = '3433de3e2864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_academics_student_id'), 'academics', ['student_id'], unique=False)
    op.create_index(op.f('ix_academics_tenant_id'), 'academics', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_attendances_student_id'), 'attendances', ['student_id'], unique=False)
    op.create_index(op.f('ix_attendances_tenant_id'), 'attendances', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_risk_prediction_logs_model_id'), 'risk_prediction_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_risk_prediction_logs_student_id'), 'risk_prediction_logs', ['student_id'], unique=False)
    op.create_index(op.f('ix_risk_prediction_logs_tenant_id'), 'risk_prediction_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_socio_economics_student_id'), 'socio_economics', ['student_id'], unique=False)
    op.create_index(op.f('ix_socio_economics_tenant_id'), 'socio_economics', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_socio_economics_tenant_id'), table_name='socio_economics')
    op.drop_index(op.f('ix_socio_economics_student_id'), table_name='socio_economics')
    op.drop_index(op.f('ix_risk_prediction_logs_tenant_id'), table_name='risk_prediction_logs')
    op.drop_index(op.f('ix_risk_prediction_logs_student_id'), table_name='risk_prediction_logs')
    op.drop_index(op.f('ix_risk_prediction_logs_model_id'), table_name='risk_prediction_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_attendances_tenant_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_student_id'), table_name='attendances')
    op.drop_index(op.f('ix_academics_tenant_id'), table_name='academics')
    op.drop_index(op.f('ix_academics_student_id'), table_name='academics')
    # ### end Alembic commands ###
